server.port=8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=kovrizhka
spring.rabbitmq.password=556028

spring.datasource.url=jdbc:postgresql://localhost:5432/kovrizhka
spring.datasource.username=kovrizhka
spring.datasource.password=556028
spring.jpa.generate-ddl=true