server.port=8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=kovrizhka
spring.rabbitmq.password=556028

spring.datasource.url=jdbc:postgresql://localhost:5432/kovrizhka
spring.datasource.username=kovrizhka
spring.datasource.password=556028
spring.jpa.generate-ddl=true

bot.token=6695998365:AAHnJ-kqAtOVZ5ikhsd34ln7qRIutftjHOw
service.file_info.uri=https://api.telegram.org/bot{token}/getFile?file_id={fileId}
service.file_storage.uri:https://api.telegram.org/file/bot{token}/{filePath}